/*
 * control.c
 *
 *  Created on: Aug 19, 2017
 *      Author: hmr
 */


#include "board.h"
#include "control.h"
#include "tdso_util.h"

#if defined(BOARD_TDSO)

#define TEST_SIG_PERIOD		1000UL // uS

//TODO: COnfigure pins

void CONTROL_SetGain(uint8_t gain){
	if(gain < CONTROL_GAIN_STAGES)
		CONTROL_SET_GAIN(gain);
}

/*
 * Configure PWM duty to generate required analog voltage to trigger comparator
 *
 */
void CONTROL_SetTriggerLevel(int16_t level){
    TIM2->CCR1 = map(level + CONTROL_TGLEVEL_ZERO, 
				CONTROL_TGLEVEL_MIN, CONTROL_TGLEVEL_MAX, 
				CONTROL_TGLEVEL_PWM_MAX, CONTROL_TGLEVEL_PWM_MIN);
}

/*
 * Configure interrupt edge to match trigger comparator output edge
 */
void CONTROL_SetTriggerEdge(uint16_t edge){

}


void CONTROL_SetVpos(Channel *ch){
	TIM2->CCR4 = map(ch->pos + CONTROL_VPOS_ZERO, 
				CONTROL_VPOS_MIN, CONTROL_VPOS_MAX, 
				CONTROL_VPOS_PWM_MIN, CONTROL_VPOS_PWM_MAX);
}

void CONTROL_Init(Dso *dso){
	CONTROL_SetGain(dso->channels[DSO_SIGNAL0_CHANNEL].scaleidx);
	CONTROL_SetTriggerLevel(dso->trigger.pos);
	CONTROL_SetVpos(&dso->channels[DSO_SIGNAL0_CHANNEL]);
}

/**
 * @brief Enables/disables 1kHz signal on PB0
 * This signal is generated by TIM3 in pwm mode
 * 
 * @param en 
 */
void CONTROL_TestSignal(uint8_t en) 
{
	GPIO_InitTypeDef GPIO_InitStruct;
	uint32_t ppre1 = (RCC->CFGR >> 11) & 7;
	ppre1 = (ppre1 == 1) ? HAL_RCC_GetPCLK1Freq() : HAL_RCC_GetPCLK1Freq() << 1;		

	if(en){
		__HAL_RCC_TIM3_CLK_ENABLE();

		TIM3->CR1 = 0; 			// Disable all
		TIM3->ARR = TEST_SIG_PERIOD - 1;
		TIM3->PSC = ppre1 / 1000 / TEST_SIG_PERIOD - 1;
		TIM3->EGR = TIM_EGR_UG; // Generate an update event to reload the Prescaler 
		TIM3->SMCR = 0;         // No slave
		TIM3->CCMR2 = TIM_CCMR2_OC3M_2 | TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3PE; // PWM Mode 1
		TIM3->CCR3 = TEST_SIG_PERIOD / 2 - 1;
		TIM3->CCER = TIM_CCER_CC3E;

		TIM3->CR1 = TIM_CR1_CEN;

		GPIO_InitStruct.Pin = TST_SIG_Pin;
    	GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    	HAL_GPIO_Init(TST_SIG_GPIO_Port, &GPIO_InitStruct);
	}else{
		__HAL_RCC_TIM3_CLK_DISABLE();

		GPIO_InitStruct.Pin = TST_SIG_Pin;
    	GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    	HAL_GPIO_Init(TST_SIG_GPIO_Port, &GPIO_InitStruct);
	}
}
#else
void CONTROL_Init(Dso *dso){}
void CONTROL_SetGain(uint8_t gain){}
void CONTROL_SelectScale(uint8_t scale){}
void CONTROL_SetTriggerLevel(int16_t level){}
void CONTROL_SetTriggerEdge(uint16_t edge) {}
void CONTROL_SetVpos(Channel *ch){}
void CONTROL_TestSignal(uint8_t en) {}
#endif
